Feature/add test cd
EyeSeeTea/d2-tools pull request #63
Opened 2024-11-13 18:58 UTC by idelcano

### :pushpin: References

-   **Issue:** Coding dojo

### :memo: Implementation
Added some test for user-permission script (In this case we change a bit the workflow and I did a manual test also to be sure that nothing is broken).

    Should ignore user if the user is in the datastore excluded users list
    Should ignore user if the user has valid roles
    Should fix user if the user has invalid authorities
    Should throw exception if the user don't have a valid user template group and fix is disabled
    Should fix add minimal group if a user dont have any control template user group
    Should push fixed usergroup if the user has no template usergroups
    Should apply minimal control template group if a user dont have any control template user group

We could continue adding test due has a lot of corner case to test.

### :video_camera: Screenshots/Screen capture

### :fire: Notes to the tester

yarn start usermonitoring run-permissions-fixer --config-file config.json

2024-12-10 09:18 UTC, xurxodev commented on src/domain/usecases/user-monitoring/permission-fixer/__tests__/RunUserPermissionUseCase.specs.ts
> +    return configThrowInvalidUsergroupException;
This function is not necessary and generate noise, you can use the variable direcly

2024-12-10 09:18 UTC, xurxodev commented on src/domain/usecases/user-monitoring/permission-fixer/__tests__/RunUserPermissionUseCase.specs.ts
> +    return configWithWrongMinimalGroup;
This function is not necessary and generate noise, you can use the variable direcly

2024-12-30 12:31 UTC, idelcano commented on src/domain/usecases/user-monitoring/permission-fixer/__tests__/RunUserPermissionUseCase.specs.ts
> +function getMetadataConfig(): PermissionFixerMetadataConfig {
All fixed

2025-02-04 13:08 UTC, xurxodev requested changes
thanks @idelcano 

It seems that the last commit broke the github action

Can you review it?

2025-02-10 07:27 UTC, idelcano commented
Hi @xurxodev, thanks for the review.

I saw it but the error originates from development:

Error: Failed to load url @dhis2/d2-i18n (resolved id: @dhis2/d2-i18n) in /home/runner/work/d2-tools/d2-tools/src/capture-core/metaData/helpers/EventProgram/getStageForEventProgram.js. Does the file exist?

All last PR was failing:
https://github.com/EyeSeeTea/d2-tools/pulls

I can check it, but I think this is a different issue, not related to my branch. Maybe it makes more sense to wait and merge a fixed development branch.

2025-02-10 11:17 UTC, xurxodev commented
@idelcano I understand that it's possible that the origin of the bug is not in your branch, however you merged with development bringing the changes from development.

Probably it was an error of someone to merge the old PR in development with this error, but I can't approve this PR if the GitHub action fails. 

Please fix the bug, probably talking with who introduced the bug. Let me know when it's fixed and I can to review the PR.

2025-03-17 10:58 UTC, xurxodev approved these changes
thanks @idelcano

2025-03-17 11:00 UTC, merged